puts "Seeding Agents"
Agent.find_or_create_by!(id: 1, name: 'Elliot Schimmel DVM', phone_number: '1-214-496-5089')
Agent.find_or_create_by(id: 2, name: 'Nelia Graham', phone_number: '193.539.7577')
Agent.find_or_create_by(id: 3, name: 'Melvin Blick', phone_number: '557-095-1452')
Agent.find_or_create_by(id: 4, name: 'Jay Hartmann', phone_number: '(734) 535-5668')
Agent.find_or_create_by(id: 5, name: 'Scot Morar', phone_number: '(279) 691-4148')
Agent.find_or_create_by(id: 6, name: 'Cassey Beier', phone_number: '(474) 777-3615')
Agent.find_or_create_by(id: 7, name: 'Morris Boyer', phone_number: '137.158.9465')
Agent.find_or_create_by(id: 8, name: 'Davis Bosco', phone_number: '(280) 680-8618')
Agent.find_or_create_by(id: 9, name: 'Marietta Lang', phone_number: '296.094.7455')
Agent.find_or_create_by(id: 10, name: 'Dr. Remedios Funk', phone_number: '1-500-079-7285')
Agent.find_or_create_by(id: 11, name: 'Sharda Cole', phone_number: '1-246-171-1355')
Agent.find_or_create_by(id: 12, name: 'Jani VonRueden', phone_number: '1-444-626-9429')
Agent.find_or_create_by(id: 13, name: 'Clorinda Farrell', phone_number: '(614) 603-6276')
Agent.find_or_create_by(id: 14, name: 'Gemma Ritchie', phone_number: '594.170.4795')
Agent.find_or_create_by(id: 15, name: 'Jennefer Hirthe', phone_number: '1-535-859-1377')
Agent.find_or_create_by(id: 16, name: 'Simon Gulgowski', phone_number: '676.706.4384')
Agent.find_or_create_by(id: 17, name: 'Stacee Bartoletti', phone_number: '256-312-4417')
Agent.find_or_create_by(id: 18, name: 'Elwood Metz', phone_number: '1-592-904-2339')
Agent.find_or_create_by(id: 19, name: 'Joanne Johnson', phone_number: '174.912.8838')
Agent.find_or_create_by(id: 20, name: 'Milo Klein', phone_number: '677.137.7019')
Agent.find_or_create_by(id: 21, name: 'Tu Jones', phone_number: '319-013-7526')
Agent.find_or_create_by(id: 22, name: 'Cameron Cruickshank', phone_number: '(200) 790-1698')
Agent.find_or_create_by(id: 23, name: 'Mr. Ernesto Rodriguez', phone_number: '576-106-0746')
Agent.find_or_create_by(id: 24, name: 'Dr. Sherwood Lehner', phone_number: '(214) 042-9715')
Agent.find_or_create_by(id: 25, name: 'Belia Kunze DVM', phone_number: '(312) 188-5862')
Agent.find_or_create_by(id: 26, name: 'Eliseo Lubowitz III', phone_number: '1-823-392-9020')
Agent.find_or_create_by(id: 27, name: 'Mrs. Lamar Satterfield', phone_number: '663.331.4191')
Agent.find_or_create_by(id: 28, name: 'Hunter Welch', phone_number: '237-101-0271')
Agent.find_or_create_by(id: 29, name: 'Chara Johns IV', phone_number: '1-836-465-1204')
Agent.find_or_create_by(id: 30, name: 'Lane Treutel Sr.', phone_number: '394-499-0004')
Agent.find_or_create_by(id: 31, name: 'Maile Rath Jr.', phone_number: '713-068-1726')
Agent.find_or_create_by(id: 32, name: 'Monique Tremblay', phone_number: '1-223-484-7856')
Agent.find_or_create_by(id: 33, name: 'Mckinley Larson', phone_number: '577.838.2303')
Agent.find_or_create_by(id: 34, name: 'Dusty Bogan', phone_number: '(358) 632-7373')
Agent.find_or_create_by(id: 35, name: 'Rosalba Rogahn', phone_number: '742-195-8692')
Agent.find_or_create_by(id: 36, name: 'Warner Nicolas', phone_number: '1-475-274-0167')
Agent.find_or_create_by(id: 37, name: 'Patricia Bins', phone_number: '650.526.9668')
Agent.find_or_create_by(id: 38, name: 'Lidia Lockman', phone_number: '1-205-336-4084')
Agent.find_or_create_by(id: 39, name: 'Doyle Bashirian', phone_number: '(382) 425-2632')
Agent.find_or_create_by(id: 40, name: 'Ellie Cole', phone_number: '(720) 543-2929')
Agent.find_or_create_by(id: 41, name: 'Fran Dickens', phone_number: '1-305-053-1716')
Agent.find_or_create_by(id: 42, name: 'Romeo Grant', phone_number: '166-530-4499')
Agent.find_or_create_by(id: 43, name: 'Carrol Kessler', phone_number: '1-688-308-1959')
Agent.find_or_create_by(id: 44, name: 'Miss Wiley Flatley', phone_number: '960.285.2223')
Agent.find_or_create_by(id: 45, name: 'Stacey Daugherty DVM', phone_number: '194.320.8085')
Agent.find_or_create_by(id: 46, name: 'Randolph Weimann', phone_number: '1-886-676-7367')
Agent.find_or_create_by(id: 47, name: 'Kent Weber', phone_number: '505.594.3565')
Agent.find_or_create_by(id: 48, name: 'Floyd Reichert', phone_number: '958-900-6479')
Agent.find_or_create_by(id: 49, name: 'Mafalda Simonis', phone_number: '(561) 615-5549')
Agent.find_or_create_by(id: 50, name: 'Mirtha Littel', phone_number: '350-334-1721')
Agent.find_or_create_by(id: 51, name: 'Damien Thiel', phone_number: '332.495.2573')
Agent.find_or_create_by(id: 52, name: 'Dayna Hilll', phone_number: '(220) 218-4786')
Agent.find_or_create_by(id: 53, name: 'Mohamed Miller', phone_number: '(591) 264-5676')
Agent.find_or_create_by(id: 54, name: 'Barton Nikolaus II', phone_number: '1-881-355-1168')
Agent.find_or_create_by(id: 55, name: 'Roxanne Roob', phone_number: '1-688-970-1501')
Agent.find_or_create_by(id: 56, name: 'Yoko Fahey', phone_number: '1-109-155-6206')
Agent.find_or_create_by(id: 57, name: 'Bobbi Goyette', phone_number: '(817) 706-3903')
Agent.find_or_create_by(id: 58, name: 'Berniece Lubowitz', phone_number: '216.861.5764')
Agent.find_or_create_by(id: 59, name: 'Bennie Sawayn', phone_number: '1-815-589-5607')
Agent.find_or_create_by(id: 60, name: 'Miss George Moore', phone_number: '518.580.3119')
Agent.find_or_create_by(id: 61, name: 'Miss Katrice Oberbrunner', phone_number: '1-658-789-4817')
Agent.find_or_create_by(id: 62, name: 'Jacqueline Rempel', phone_number: '(216) 920-0011')
Agent.find_or_create_by(id: 63, name: 'Mr. Vallie Rohan', phone_number: '1-193-166-2013')
Agent.find_or_create_by(id: 64, name: 'Jermaine Hoppe', phone_number: '(719) 081-8157')
Agent.find_or_create_by(id: 65, name: 'Trent Leuschke', phone_number: '(227) 470-1589')
Agent.find_or_create_by(id: 66, name: 'Hobert Ryan DDS', phone_number: '501-950-6320')
Agent.find_or_create_by(id: 67, name: 'Vi Wyman', phone_number: '(702) 306-3966')
Agent.find_or_create_by(id: 68, name: 'Shaunda Ratke', phone_number: '1-809-043-8605')
Agent.find_or_create_by(id: 69, name: 'Alesia Wintheiser', phone_number: '(494) 630-4602')
Agent.find_or_create_by(id: 70, name: 'Mitchell Lubowitz', phone_number: '(279) 047-8430')
Agent.find_or_create_by(id: 71, name: 'Mr. Azalee Hoeger', phone_number: '(534) 216-9364')
Agent.find_or_create_by(id: 72, name: 'Marty Gorczany', phone_number: '564.789.5501')
Agent.find_or_create_by(id: 73, name: 'Rosalind Zulauf', phone_number: '(201) 318-7865')
Agent.find_or_create_by(id: 74, name: 'Kandace Collins', phone_number: '584-956-4034')
Agent.find_or_create_by(id: 75, name: 'Loreen Fahey MD', phone_number: '(442) 108-4639')
Agent.find_or_create_by(id: 76, name: 'Hayden Wunsch', phone_number: '541-495-8332')
Agent.find_or_create_by(id: 77, name: 'Necole Klein', phone_number: '(339) 961-9837')
Agent.find_or_create_by(id: 78, name: 'Miss Calvin Jenkins', phone_number: '(759) 256-2968')
Agent.find_or_create_by(id: 79, name: 'Alfredia Fadel', phone_number: '1-629-759-4160')
Agent.find_or_create_by(id: 80, name: 'Hoa Runolfsdottir', phone_number: '420.070.3836')
Agent.find_or_create_by(id: 81, name: 'Dotty McLaughlin', phone_number: '709-179-2300')
Agent.find_or_create_by(id: 82, name: 'Ty Volkman', phone_number: '453-328-2136')
Agent.find_or_create_by(id: 83, name: 'Tyler Rempel', phone_number: '977-804-7504')
Agent.find_or_create_by(id: 84, name: 'Lavina Lindgren DDS', phone_number: '905-178-7869')
Agent.find_or_create_by(id: 85, name: 'Abdul Schaefer', phone_number: '(233) 355-4178')
Agent.find_or_create_by(id: 86, name: 'Mr. Kristopher Goldner', phone_number: '(200) 965-7354')
Agent.find_or_create_by(id: 87, name: 'Ana MacGyver', phone_number: '(924) 767-6900')
Agent.find_or_create_by(id: 88, name: 'Jerold McKenzie', phone_number: '1-238-903-9270')
Agent.find_or_create_by(id: 89, name: 'Ericka Yost', phone_number: '563.874.2068')
Agent.find_or_create_by(id: 90, name: 'Ms. Francisco Braun', phone_number: '(616) 759-1103')
Agent.find_or_create_by(id: 91, name: 'Mrs. Kari Batz', phone_number: '1-333-845-1607')
Agent.find_or_create_by(id: 92, name: 'Diane Bahringer', phone_number: '(703) 875-8777')
Agent.find_or_create_by(id: 93, name: 'Arden Quigley', phone_number: '472-612-7979')
Agent.find_or_create_by(id: 94, name: 'Kenda Ernser', phone_number: '524-604-2021')
Agent.find_or_create_by(id: 95, name: 'Thad Walsh', phone_number: '1-232-473-1388')
Agent.find_or_create_by(id: 96, name: 'Rich Gorczany', phone_number: '(271) 375-4035')
Agent.find_or_create_by(id: 97, name: 'Xuan Schiller', phone_number: '1-262-529-6931')
Agent.find_or_create_by(id: 98, name: 'Anjelica Weber', phone_number: '(792) 429-0061')
Agent.find_or_create_by(id: 99, name: 'Weston Corwin', phone_number: '(423) 142-5142')
Agent.find_or_create_by(id: 100, name: 'Allen Littel', phone_number: '1-799-597-9021')
Agent.find_or_create_by(id: 101, name: 'Karyn Hoeger DDS', phone_number: '(870) 815-8233')
Agent.find_or_create_by(id: 102, name: 'Mohamed Halvorson Sr.', phone_number: '1-307-437-6377')
Agent.find_or_create_by(id: 103, name: 'Jeremy Mosciski', phone_number: '1-227-267-6873')
Agent.find_or_create_by(id: 104, name: 'Marisol Lubowitz', phone_number: '1-424-673-0279')
Agent.find_or_create_by(id: 105, name: 'Rex Hammes', phone_number: '502.464.0919')
Agent.find_or_create_by(id: 106, name: 'Whitney Treutel', phone_number: '(662) 928-5292')
Agent.find_or_create_by(id: 107, name: 'Izola Cummerata V', phone_number: '499.949.0119')
Agent.find_or_create_by(id: 108, name: 'Mason Hamill', phone_number: '191.450.4986')
Agent.find_or_create_by(id: 109, name: 'Romeo Morissette DVM', phone_number: '261-030-3639')
Agent.find_or_create_by(id: 110, name: 'Mrs. Elvis Swift', phone_number: '1-276-602-1034')
Agent.find_or_create_by(id: 111, name: 'Kristofer Lowe', phone_number: '(777) 570-0650')
Agent.find_or_create_by(id: 112, name: 'Ernesto Morar MD', phone_number: '1-413-733-6992')
Agent.find_or_create_by(id: 113, name: 'Bette Morar', phone_number: '(316) 034-0019')
Agent.find_or_create_by(id: 114, name: 'Isobel McLaughlin PhD', phone_number: '1-665-503-8933')
Agent.find_or_create_by(id: 115, name: 'Justa Nicolas DDS', phone_number: '989-889-9908')
Agent.find_or_create_by(id: 116, name: 'Frank Prohaska', phone_number: '809-300-2481')
Agent.find_or_create_by(id: 117, name: 'Teodoro Beahan', phone_number: '(453) 263-7957')
Agent.find_or_create_by(id: 118, name: 'Deangelo Hermiston', phone_number: '1-756-870-1969')
Agent.find_or_create_by(id: 119, name: 'Wm Breitenberg', phone_number: '223-404-1670')
Agent.find_or_create_by(id: 120, name: 'Elsy Vandervort', phone_number: '908.065.9697')

puts "Seeding Industries"
Industry.find_or_create_by(id: 1, name: 'Underwater Electrical Wiring')
Industry.find_or_create_by(id: 2, name: 'Exterior Painting of Watertowers')
Industry.find_or_create_by(id: 3, name: 'Professional Tight-Rope Walking')
Industry.find_or_create_by(id: 4, name: 'Pencil Sharpening')
Industry.find_or_create_by(id: 5, name: 'Underwater Welding')
Industry.find_or_create_by(id: 6, name: 'Human Crash-test Dummy')
Industry.find_or_create_by(id: 7, name: 'Professional Beer Taste-Tester')
Industry.find_or_create_by(id: 8, name: 'Building Construction')
Industry.find_or_create_by(id: 9, name: 'Artisanal Cheesemaking')
Industry.find_or_create_by(id: 10, name: 'Ruby on Rails Software Development')
Industry.find_or_create_by(id: 11, name: 'Libraries')
Industry.find_or_create_by(id: 12, name: 'Supermarkets')
Industry.find_or_create_by(id: 13, name: 'Religious Institutions')
Industry.find_or_create_by(id: 14, name: 'Legal Services')
Industry.find_or_create_by(id: 15, name: 'Medical Practice')
Industry.find_or_create_by(id: 16, name: 'Research')
Industry.find_or_create_by(id: 17, name: 'Information Technology and Services')
Industry.find_or_create_by(id: 18, name: 'Professional Training & Coaching')
Industry.find_or_create_by(id: 19, name: 'Individual & Family Services')
Industry.find_or_create_by(id: 20, name: 'Animation')
Industry.find_or_create_by(id: 21, name: 'Philanthropy')
Industry.find_or_create_by(id: 22, name: 'Mechanical or Industrial Engineering')
Industry.find_or_create_by(id: 23, name: 'International Affairs')
Industry.find_or_create_by(id: 24, name: 'Import and Export')
Industry.find_or_create_by(id: 25, name: 'Capital Markets')
Industry.find_or_create_by(id: 26, name: 'Environmental Services')
Industry.find_or_create_by(id: 27, name: 'Glass, Ceramics & Concrete')
Industry.find_or_create_by(id: 28, name: 'Music')
Industry.find_or_create_by(id: 29, name: 'Human Resources')
Industry.find_or_create_by(id: 30, name: 'Accounting')
Industry.find_or_create_by(id: 31, name: 'Law Enforcement')
Industry.find_or_create_by(id: 32, name: 'Outsourcing / Offshoring')
Industry.find_or_create_by(id: 33, name: 'Newspapers')

puts "Seeding Carriers"
Carrier.find_or_create_by(name: 'FarmInsure')
Carrier.find_by_name('FarmInsure').industries << Industry.find_by_name('Environmental Services')
Carrier.find_by_name('FarmInsure').industries << Industry.find_by_name('Supermarkets')
Carrier.find_by_name('FarmInsure').industries << Industry.find_by_name('Import and Export')
Carrier.find_by_name('FarmInsure').industries << Industry.find_by_name('Underwater Electrical Wiring')
Carrier.find_by_name('FarmInsure').industries << Industry.find_by_name('Exterior Painting of Watertowers')
Carrier.find_by_name('FarmInsure').industries << Industry.find_by_name('Medical Practice')
Carrier.find_by_name('FarmInsure').industries << Industry.find_by_name('International Affairs')
Carrier.find_or_create_by(name: 'Homestate')
Carrier.find_by_name('Homestate').industries << Industry.find_by_name('Professional Training & Coaching')
Carrier.find_by_name('Homestate').industries << Industry.find_by_name('Research')
Carrier.find_by_name('Homestate').industries << Industry.find_by_name('Pencil Sharpening')
Carrier.find_by_name('Homestate').industries << Industry.find_by_name('Import and Export')
Carrier.find_by_name('Homestate').industries << Industry.find_by_name('Animation')
Carrier.find_by_name('Homestate').industries << Industry.find_by_name('Mechanical or Industrial Engineering')
Carrier.find_by_name('Homestate').industries << Industry.find_by_name('Information Technology and Services')
Carrier.find_or_create_by(name: 'Statewide')
Carrier.find_by_name('Statewide').industries << Industry.find_by_name('Pencil Sharpening')
Carrier.find_by_name('Statewide').industries << Industry.find_by_name('Accounting')
Carrier.find_by_name('Statewide').industries << Industry.find_by_name('Information Technology and Services')
Carrier.find_by_name('Statewide').industries << Industry.find_by_name('Ruby on Rails Software Development')
Carrier.find_or_create_by(name: 'Freedom Insurance Company')
Carrier.find_by_name('Freedom Insurance Company').industries << Industry.find_by_name('Environmental Services')
Carrier.find_by_name('Freedom Insurance Company').industries << Industry.find_by_name('Import and Export')
Carrier.find_by_name('Freedom Insurance Company').industries << Industry.find_by_name('Human Resources')
Carrier.find_by_name('Freedom Insurance Company').industries << Industry.find_by_name('Music')
Carrier.find_or_create_by(name: 'Cold Weather Insurance')
Carrier.find_by_name('Cold Weather Insurance').industries << Industry.find_by_name('Professional Tight-Rope Walking')
Carrier.find_by_name('Cold Weather Insurance').industries << Industry.find_by_name('Accounting')
Carrier.find_by_name('Cold Weather Insurance').industries << Industry.find_by_name('Mechanical or Industrial Engineering')
Carrier.find_by_name('Cold Weather Insurance').industries << Industry.find_by_name('Legal Services')
Carrier.find_by_name('Cold Weather Insurance').industries << Industry.find_by_name('Pencil Sharpening')
Carrier.find_by_name('Cold Weather Insurance').industries << Industry.find_by_name('Professional Training & Coaching')
Carrier.find_by_name('Cold Weather Insurance').industries << Industry.find_by_name('Religious Institutions')
Carrier.find_or_create_by(name: 'Iguana Insure')
Carrier.find_by_name('Iguana Insure').industries << Industry.find_by_name('International Affairs')
Carrier.find_by_name('Iguana Insure').industries << Industry.find_by_name('Building Construction')
Carrier.find_by_name('Iguana Insure').industries << Industry.find_by_name('Legal Services')
Carrier.find_by_name('Iguana Insure').industries << Industry.find_by_name('Professional Beer Taste-Tester')
Carrier.find_or_create_by(name: 'Allen & Associates')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('Medical Practice')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('Outsourcing / Offshoring')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('Philanthropy')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('Exterior Painting of Watertowers')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('Human Crash-test Dummy')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('Professional Training & Coaching')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('International Affairs')
Carrier.find_by_name('Allen & Associates').industries << Industry.find_by_name('Music')
Carrier.find_or_create_by(name: 'Safestate')
Carrier.find_by_name('Safestate').industries << Industry.find_by_name('Religious Institutions')
Carrier.find_by_name('Safestate').industries << Industry.find_by_name('Research')
Carrier.find_by_name('Safestate').industries << Industry.find_by_name('Philanthropy')
Carrier.find_by_name('Safestate').industries << Industry.find_by_name('Accounting')
Carrier.find_or_create_by(name: 'Prestige Worldwide')
Carrier.find_by_name('Prestige Worldwide').industries << Industry.find_by_name('Philanthropy')
Carrier.find_by_name('Prestige Worldwide').industries << Industry.find_by_name('International Affairs')
Carrier.find_by_name('Prestige Worldwide').industries << Industry.find_by_name('Animation')
Carrier.find_by_name('Prestige Worldwide').industries << Industry.find_by_name('Glass, Ceramics & Concrete')
Carrier.find_by_name('Prestige Worldwide').industries << Industry.find_by_name('Underwater Electrical Wiring')
Carrier.find_or_create_by(name: 'Polaris International Risk')
Carrier.find_by_name('Polaris International Risk').industries << Industry.find_by_name('Professional Beer Taste-Tester')
Carrier.find_by_name('Polaris International Risk').industries << Industry.find_by_name('Libraries')
Carrier.find_by_name('Polaris International Risk').industries << Industry.find_by_name('Legal Services')
Carrier.find_by_name('Polaris International Risk').industries << Industry.find_by_name('Building Construction')
Carrier.find_by_name('Polaris International Risk').industries << Industry.find_by_name('Outsourcing / Offshoring')
Carrier.find_or_create_by(name: 'Big City Business Insurance')
Carrier.find_by_name('Big City Business Insurance').industries << Industry.find_by_name('Medical Practice')
Carrier.find_by_name('Big City Business Insurance').industries << Industry.find_by_name('Supermarkets')
Carrier.find_by_name('Big City Business Insurance').industries << Industry.find_by_name('Building Construction')
Carrier.find_by_name('Big City Business Insurance').industries << Industry.find_by_name('Legal Services')
Carrier.find_or_create_by(name: 'PenguinTech')
Carrier.find_by_name('PenguinTech').industries << Industry.find_by_name('Libraries')
Carrier.find_by_name('PenguinTech').industries << Industry.find_by_name('Accounting')
Carrier.find_by_name('PenguinTech').industries << Industry.find_by_name('Outsourcing / Offshoring')

puts "Seeding Licenses"
License.find_or_create_by(agent_id: 1, state: "AL")
License.find_or_create_by(agent_id: 1, state: "PA")
License.find_or_create_by(agent_id: 1, state: "MA")
License.find_or_create_by(agent_id: 1, state: "WA")
License.find_or_create_by(agent_id: 1, state: "OK")
License.find_or_create_by(agent_id: 1, state: "WI")
Agent.find(1).carriers << Carrier.find_by_name('Homestate')
Agent.find(1).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 2, state: "MN")
License.find_or_create_by(agent_id: 2, state: "MS")
License.find_or_create_by(agent_id: 2, state: "NE")
License.find_or_create_by(agent_id: 2, state: "OK")
License.find_or_create_by(agent_id: 2, state: "KS")
Agent.find(2).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(2).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(2).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 3, state: "WA")
License.find_or_create_by(agent_id: 3, state: "WY")
Agent.find(3).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(3).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(3).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 4, state: "AZ")
License.find_or_create_by(agent_id: 4, state: "WV")
License.find_or_create_by(agent_id: 4, state: "NH")
License.find_or_create_by(agent_id: 4, state: "OR")
License.find_or_create_by(agent_id: 4, state: "UT")
License.find_or_create_by(agent_id: 4, state: "LA")
License.find_or_create_by(agent_id: 4, state: "SC")
License.find_or_create_by(agent_id: 4, state: "NV")
Agent.find(4).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(4).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(4).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 5, state: "AL")
License.find_or_create_by(agent_id: 5, state: "VT")
License.find_or_create_by(agent_id: 5, state: "KY")
License.find_or_create_by(agent_id: 5, state: "IN")
License.find_or_create_by(agent_id: 5, state: "OH")
License.find_or_create_by(agent_id: 5, state: "LA")
License.find_or_create_by(agent_id: 5, state: "NY")
License.find_or_create_by(agent_id: 5, state: "GA")
Agent.find(5).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(5).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(5).carriers << Carrier.find_by_name('Safestate')
Agent.find(5).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 6, state: "PA")
License.find_or_create_by(agent_id: 6, state: "TN")
License.find_or_create_by(agent_id: 6, state: "NH")
License.find_or_create_by(agent_id: 6, state: "OH")
License.find_or_create_by(agent_id: 6, state: "UT")
License.find_or_create_by(agent_id: 6, state: "GA")
License.find_or_create_by(agent_id: 6, state: "MN")
Agent.find(6).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(6).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(6).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 7, state: "NM")
License.find_or_create_by(agent_id: 7, state: "TN")
License.find_or_create_by(agent_id: 7, state: "RI")
License.find_or_create_by(agent_id: 7, state: "LA")
License.find_or_create_by(agent_id: 7, state: "TX")
License.find_or_create_by(agent_id: 7, state: "DE")
Agent.find(7).carriers << Carrier.find_by_name('Safestate')
Agent.find(7).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 8, state: "CO")
License.find_or_create_by(agent_id: 8, state: "NJ")
License.find_or_create_by(agent_id: 8, state: "MS")
License.find_or_create_by(agent_id: 8, state: "AK")
Agent.find(8).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(8).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 9, state: "MD")
License.find_or_create_by(agent_id: 9, state: "TX")
License.find_or_create_by(agent_id: 9, state: "NE")
License.find_or_create_by(agent_id: 9, state: "AK")
Agent.find(9).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 10, state: "MD")
License.find_or_create_by(agent_id: 10, state: "WI")
License.find_or_create_by(agent_id: 10, state: "ID")
License.find_or_create_by(agent_id: 10, state: "TN")
License.find_or_create_by(agent_id: 10, state: "NY")
License.find_or_create_by(agent_id: 10, state: "WA")
License.find_or_create_by(agent_id: 10, state: "NC")
Agent.find(10).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(10).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 11, state: "KS")
License.find_or_create_by(agent_id: 11, state: "AL")
Agent.find(11).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(11).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(11).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 12, state: "OR")
License.find_or_create_by(agent_id: 12, state: "NV")
License.find_or_create_by(agent_id: 12, state: "OK")
License.find_or_create_by(agent_id: 12, state: "OH")
License.find_or_create_by(agent_id: 12, state: "AL")
License.find_or_create_by(agent_id: 12, state: "SD")
License.find_or_create_by(agent_id: 12, state: "NE")
Agent.find(12).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(12).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 13, state: "LA")
License.find_or_create_by(agent_id: 13, state: "HI")
License.find_or_create_by(agent_id: 13, state: "OR")
License.find_or_create_by(agent_id: 13, state: "DE")
License.find_or_create_by(agent_id: 13, state: "ID")
License.find_or_create_by(agent_id: 13, state: "AR")
Agent.find(13).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(13).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(13).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 14, state: "MI")
License.find_or_create_by(agent_id: 14, state: "OH")
License.find_or_create_by(agent_id: 14, state: "CT")
Agent.find(14).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(14).carriers << Carrier.find_by_name('Homestate')
Agent.find(14).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 15, state: "NY")
License.find_or_create_by(agent_id: 15, state: "CT")
Agent.find(15).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(15).carriers << Carrier.find_by_name('Statewide')
Agent.find(15).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 16, state: "CO")
License.find_or_create_by(agent_id: 16, state: "PA")
License.find_or_create_by(agent_id: 16, state: "IL")
License.find_or_create_by(agent_id: 16, state: "VT")
License.find_or_create_by(agent_id: 16, state: "HI")
Agent.find(16).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 17, state: "NY")
License.find_or_create_by(agent_id: 17, state: "TX")
Agent.find(17).carriers << Carrier.find_by_name('Homestate')
Agent.find(17).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 18, state: "ND")
License.find_or_create_by(agent_id: 18, state: "AZ")
License.find_or_create_by(agent_id: 18, state: "OR")
Agent.find(18).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(18).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(18).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 19, state: "KY")
License.find_or_create_by(agent_id: 19, state: "MN")
License.find_or_create_by(agent_id: 19, state: "MO")
License.find_or_create_by(agent_id: 19, state: "RI")
License.find_or_create_by(agent_id: 19, state: "AZ")
License.find_or_create_by(agent_id: 19, state: "VA")
License.find_or_create_by(agent_id: 19, state: "FL")
Agent.find(19).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(19).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(19).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 20, state: "RI")
License.find_or_create_by(agent_id: 20, state: "NY")
License.find_or_create_by(agent_id: 20, state: "OK")
License.find_or_create_by(agent_id: 20, state: "OH")
License.find_or_create_by(agent_id: 20, state: "AR")
License.find_or_create_by(agent_id: 20, state: "TN")
License.find_or_create_by(agent_id: 20, state: "KS")
License.find_or_create_by(agent_id: 20, state: "WI")
Agent.find(20).carriers << Carrier.find_by_name('Safestate')
Agent.find(20).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 21, state: "ND")
License.find_or_create_by(agent_id: 21, state: "NM")
License.find_or_create_by(agent_id: 21, state: "CA")
License.find_or_create_by(agent_id: 21, state: "WV")
License.find_or_create_by(agent_id: 21, state: "ID")
License.find_or_create_by(agent_id: 21, state: "MO")
License.find_or_create_by(agent_id: 21, state: "WA")
Agent.find(21).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(21).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 22, state: "HI")
License.find_or_create_by(agent_id: 22, state: "WY")
License.find_or_create_by(agent_id: 22, state: "ME")
License.find_or_create_by(agent_id: 22, state: "RI")
License.find_or_create_by(agent_id: 22, state: "SD")
License.find_or_create_by(agent_id: 22, state: "OK")
Agent.find(22).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(22).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(22).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 23, state: "WI")
License.find_or_create_by(agent_id: 23, state: "CT")
License.find_or_create_by(agent_id: 23, state: "IL")
License.find_or_create_by(agent_id: 23, state: "FL")
License.find_or_create_by(agent_id: 23, state: "HI")
Agent.find(23).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(23).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(23).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 24, state: "VT")
License.find_or_create_by(agent_id: 24, state: "IL")
License.find_or_create_by(agent_id: 24, state: "IN")
License.find_or_create_by(agent_id: 24, state: "NJ")
License.find_or_create_by(agent_id: 24, state: "DE")
License.find_or_create_by(agent_id: 24, state: "ND")
License.find_or_create_by(agent_id: 24, state: "MS")
Agent.find(24).carriers << Carrier.find_by_name('Safestate')
Agent.find(24).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 25, state: "ME")
License.find_or_create_by(agent_id: 25, state: "LA")
License.find_or_create_by(agent_id: 25, state: "AR")
License.find_or_create_by(agent_id: 25, state: "MD")
License.find_or_create_by(agent_id: 25, state: "FL")
Agent.find(25).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(25).carriers << Carrier.find_by_name('Statewide')
Agent.find(25).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 26, state: "WV")
License.find_or_create_by(agent_id: 26, state: "DE")
License.find_or_create_by(agent_id: 26, state: "NJ")
License.find_or_create_by(agent_id: 26, state: "CO")
License.find_or_create_by(agent_id: 26, state: "CA")
Agent.find(26).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(26).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(26).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 27, state: "OR")
License.find_or_create_by(agent_id: 27, state: "IL")
License.find_or_create_by(agent_id: 27, state: "NH")
License.find_or_create_by(agent_id: 27, state: "TX")
License.find_or_create_by(agent_id: 27, state: "KY")
License.find_or_create_by(agent_id: 27, state: "CA")
Agent.find(27).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(27).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 28, state: "VA")
License.find_or_create_by(agent_id: 28, state: "KY")
License.find_or_create_by(agent_id: 28, state: "TX")
License.find_or_create_by(agent_id: 28, state: "WI")
Agent.find(28).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(28).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 29, state: "NJ")
License.find_or_create_by(agent_id: 29, state: "PA")
Agent.find(29).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(29).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(29).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 30, state: "CA")
License.find_or_create_by(agent_id: 30, state: "NJ")
License.find_or_create_by(agent_id: 30, state: "IN")
License.find_or_create_by(agent_id: 30, state: "ME")
License.find_or_create_by(agent_id: 30, state: "ID")
Agent.find(30).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(30).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(30).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 31, state: "GA")
License.find_or_create_by(agent_id: 31, state: "UT")
License.find_or_create_by(agent_id: 31, state: "AZ")
Agent.find(31).carriers << Carrier.find_by_name('Homestate')
Agent.find(31).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 32, state: "WA")
License.find_or_create_by(agent_id: 32, state: "HI")
License.find_or_create_by(agent_id: 32, state: "TX")
License.find_or_create_by(agent_id: 32, state: "ID")
License.find_or_create_by(agent_id: 32, state: "ND")
License.find_or_create_by(agent_id: 32, state: "IN")
License.find_or_create_by(agent_id: 32, state: "TN")
License.find_or_create_by(agent_id: 32, state: "KS")
Agent.find(32).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(32).carriers << Carrier.find_by_name('Big City Business Insurance')
License.find_or_create_by(agent_id: 33, state: "NH")
License.find_or_create_by(agent_id: 33, state: "MN")
License.find_or_create_by(agent_id: 33, state: "MA")
License.find_or_create_by(agent_id: 33, state: "MD")
License.find_or_create_by(agent_id: 33, state: "PA")
License.find_or_create_by(agent_id: 33, state: "AK")
License.find_or_create_by(agent_id: 33, state: "NJ")
License.find_or_create_by(agent_id: 33, state: "MO")
Agent.find(33).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(33).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(33).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 34, state: "CO")
License.find_or_create_by(agent_id: 34, state: "TN")
License.find_or_create_by(agent_id: 34, state: "UT")
Agent.find(34).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(34).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 35, state: "ND")
License.find_or_create_by(agent_id: 35, state: "KY")
License.find_or_create_by(agent_id: 35, state: "RI")
Agent.find(35).carriers << Carrier.find_by_name('Homestate')
Agent.find(35).carriers << Carrier.find_by_name('Statewide')
Agent.find(35).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 36, state: "AL")
License.find_or_create_by(agent_id: 36, state: "DE")
License.find_or_create_by(agent_id: 36, state: "VA")
License.find_or_create_by(agent_id: 36, state: "NE")
Agent.find(36).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(36).carriers << Carrier.find_by_name('Big City Business Insurance')
License.find_or_create_by(agent_id: 37, state: "NV")
License.find_or_create_by(agent_id: 37, state: "MI")
License.find_or_create_by(agent_id: 37, state: "KY")
Agent.find(37).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(37).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(37).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 38, state: "TN")
License.find_or_create_by(agent_id: 38, state: "WI")
License.find_or_create_by(agent_id: 38, state: "WV")
Agent.find(38).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(38).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(38).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(38).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 39, state: "VA")
License.find_or_create_by(agent_id: 39, state: "GA")
License.find_or_create_by(agent_id: 39, state: "NH")
License.find_or_create_by(agent_id: 39, state: "KY")
Agent.find(39).carriers << Carrier.find_by_name('Statewide')
Agent.find(39).carriers << Carrier.find_by_name('Safestate')
Agent.find(39).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 40, state: "AZ")
License.find_or_create_by(agent_id: 40, state: "NE")
License.find_or_create_by(agent_id: 40, state: "MN")
License.find_or_create_by(agent_id: 40, state: "OH")
License.find_or_create_by(agent_id: 40, state: "WI")
License.find_or_create_by(agent_id: 40, state: "KS")
Agent.find(40).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(40).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 41, state: "CO")
License.find_or_create_by(agent_id: 41, state: "WI")
License.find_or_create_by(agent_id: 41, state: "NM")
License.find_or_create_by(agent_id: 41, state: "MT")
License.find_or_create_by(agent_id: 41, state: "HI")
Agent.find(41).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(41).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 42, state: "SC")
License.find_or_create_by(agent_id: 42, state: "AK")
License.find_or_create_by(agent_id: 42, state: "WV")
Agent.find(42).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(42).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 43, state: "CA")
License.find_or_create_by(agent_id: 43, state: "MA")
Agent.find(43).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(43).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 44, state: "NE")
License.find_or_create_by(agent_id: 44, state: "CA")
License.find_or_create_by(agent_id: 44, state: "IL")
License.find_or_create_by(agent_id: 44, state: "NJ")
License.find_or_create_by(agent_id: 44, state: "GA")
License.find_or_create_by(agent_id: 44, state: "NH")
License.find_or_create_by(agent_id: 44, state: "LA")
Agent.find(44).carriers << Carrier.find_by_name('Safestate')
Agent.find(44).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 45, state: "NV")
License.find_or_create_by(agent_id: 45, state: "MT")
License.find_or_create_by(agent_id: 45, state: "DE")
Agent.find(45).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(45).carriers << Carrier.find_by_name('Big City Business Insurance')
License.find_or_create_by(agent_id: 46, state: "DE")
License.find_or_create_by(agent_id: 46, state: "AR")
License.find_or_create_by(agent_id: 46, state: "CT")
License.find_or_create_by(agent_id: 46, state: "MT")
License.find_or_create_by(agent_id: 46, state: "WI")
Agent.find(46).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(46).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(46).carriers << Carrier.find_by_name('Homestate')
Agent.find(46).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 47, state: "OR")
License.find_or_create_by(agent_id: 47, state: "NM")
Agent.find(47).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(47).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 48, state: "HI")
License.find_or_create_by(agent_id: 48, state: "FL")
License.find_or_create_by(agent_id: 48, state: "IL")
License.find_or_create_by(agent_id: 48, state: "MI")
License.find_or_create_by(agent_id: 48, state: "WV")
License.find_or_create_by(agent_id: 48, state: "CO")
License.find_or_create_by(agent_id: 48, state: "DE")
License.find_or_create_by(agent_id: 48, state: "VA")
Agent.find(48).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(48).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(48).carriers << Carrier.find_by_name('Homestate')
Agent.find(48).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 49, state: "ID")
License.find_or_create_by(agent_id: 49, state: "MS")
License.find_or_create_by(agent_id: 49, state: "OR")
License.find_or_create_by(agent_id: 49, state: "TX")
License.find_or_create_by(agent_id: 49, state: "AZ")
License.find_or_create_by(agent_id: 49, state: "AL")
License.find_or_create_by(agent_id: 49, state: "FL")
Agent.find(49).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(49).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 50, state: "VA")
License.find_or_create_by(agent_id: 50, state: "NV")
License.find_or_create_by(agent_id: 50, state: "WV")
License.find_or_create_by(agent_id: 50, state: "CA")
Agent.find(50).carriers << Carrier.find_by_name('Homestate')
Agent.find(50).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(50).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 51, state: "NV")
License.find_or_create_by(agent_id: 51, state: "MT")
License.find_or_create_by(agent_id: 51, state: "OR")
License.find_or_create_by(agent_id: 51, state: "KS")
License.find_or_create_by(agent_id: 51, state: "IN")
License.find_or_create_by(agent_id: 51, state: "DE")
Agent.find(51).carriers << Carrier.find_by_name('Safestate')
Agent.find(51).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(51).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(51).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 52, state: "VA")
License.find_or_create_by(agent_id: 52, state: "OH")
License.find_or_create_by(agent_id: 52, state: "ID")
License.find_or_create_by(agent_id: 52, state: "MO")
License.find_or_create_by(agent_id: 52, state: "MI")
License.find_or_create_by(agent_id: 52, state: "WV")
Agent.find(52).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(52).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(52).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 53, state: "TX")
License.find_or_create_by(agent_id: 53, state: "CA")
License.find_or_create_by(agent_id: 53, state: "RI")
License.find_or_create_by(agent_id: 53, state: "ND")
License.find_or_create_by(agent_id: 53, state: "OK")
License.find_or_create_by(agent_id: 53, state: "AZ")
Agent.find(53).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 54, state: "NJ")
License.find_or_create_by(agent_id: 54, state: "OH")
License.find_or_create_by(agent_id: 54, state: "MO")
License.find_or_create_by(agent_id: 54, state: "RI")
License.find_or_create_by(agent_id: 54, state: "TX")
Agent.find(54).carriers << Carrier.find_by_name('Safestate')
Agent.find(54).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(54).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(54).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 55, state: "AK")
License.find_or_create_by(agent_id: 55, state: "IL")
Agent.find(55).carriers << Carrier.find_by_name('Safestate')
Agent.find(55).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(55).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 56, state: "TN")
License.find_or_create_by(agent_id: 56, state: "IA")
License.find_or_create_by(agent_id: 56, state: "HI")
Agent.find(56).carriers << Carrier.find_by_name('Homestate')
Agent.find(56).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(56).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 57, state: "NY")
License.find_or_create_by(agent_id: 57, state: "VA")
Agent.find(57).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(57).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 58, state: "CA")
License.find_or_create_by(agent_id: 58, state: "NE")
License.find_or_create_by(agent_id: 58, state: "ME")
License.find_or_create_by(agent_id: 58, state: "MN")
License.find_or_create_by(agent_id: 58, state: "NH")
Agent.find(58).carriers << Carrier.find_by_name('Safestate')
Agent.find(58).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 59, state: "ND")
License.find_or_create_by(agent_id: 59, state: "ID")
License.find_or_create_by(agent_id: 59, state: "IN")
Agent.find(59).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(59).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 60, state: "NJ")
License.find_or_create_by(agent_id: 60, state: "MT")
License.find_or_create_by(agent_id: 60, state: "TX")
License.find_or_create_by(agent_id: 60, state: "HI")
License.find_or_create_by(agent_id: 60, state: "TN")
License.find_or_create_by(agent_id: 60, state: "MN")
Agent.find(60).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(60).carriers << Carrier.find_by_name('Homestate')
Agent.find(60).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 61, state: "WI")
License.find_or_create_by(agent_id: 61, state: "HI")
License.find_or_create_by(agent_id: 61, state: "ID")
License.find_or_create_by(agent_id: 61, state: "MA")
License.find_or_create_by(agent_id: 61, state: "OH")
Agent.find(61).carriers << Carrier.find_by_name('Statewide')
Agent.find(61).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(61).carriers << Carrier.find_by_name('Big City Business Insurance')
License.find_or_create_by(agent_id: 62, state: "GA")
License.find_or_create_by(agent_id: 62, state: "KS")
License.find_or_create_by(agent_id: 62, state: "WV")
License.find_or_create_by(agent_id: 62, state: "OR")
License.find_or_create_by(agent_id: 62, state: "WA")
License.find_or_create_by(agent_id: 62, state: "ID")
License.find_or_create_by(agent_id: 62, state: "NY")
License.find_or_create_by(agent_id: 62, state: "CT")
Agent.find(62).carriers << Carrier.find_by_name('Statewide')
Agent.find(62).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 63, state: "WY")
License.find_or_create_by(agent_id: 63, state: "DE")
License.find_or_create_by(agent_id: 63, state: "NM")
Agent.find(63).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(63).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(63).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 64, state: "CO")
License.find_or_create_by(agent_id: 64, state: "ID")
License.find_or_create_by(agent_id: 64, state: "WV")
Agent.find(64).carriers << Carrier.find_by_name('Safestate')
Agent.find(64).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 65, state: "TN")
License.find_or_create_by(agent_id: 65, state: "AR")
License.find_or_create_by(agent_id: 65, state: "KS")
License.find_or_create_by(agent_id: 65, state: "MN")
License.find_or_create_by(agent_id: 65, state: "SC")
License.find_or_create_by(agent_id: 65, state: "ND")
License.find_or_create_by(agent_id: 65, state: "IL")
License.find_or_create_by(agent_id: 65, state: "IA")
Agent.find(65).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(65).carriers << Carrier.find_by_name('Statewide')
Agent.find(65).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 66, state: "OH")
License.find_or_create_by(agent_id: 66, state: "LA")
License.find_or_create_by(agent_id: 66, state: "IN")
License.find_or_create_by(agent_id: 66, state: "CO")
Agent.find(66).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(66).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(66).carriers << Carrier.find_by_name('Statewide')
Agent.find(66).carriers << Carrier.find_by_name('Safestate')
License.find_or_create_by(agent_id: 67, state: "CO")
License.find_or_create_by(agent_id: 67, state: "OK")
License.find_or_create_by(agent_id: 67, state: "KS")
Agent.find(67).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(67).carriers << Carrier.find_by_name('Safestate')
License.find_or_create_by(agent_id: 68, state: "AR")
License.find_or_create_by(agent_id: 68, state: "NV")
License.find_or_create_by(agent_id: 68, state: "KS")
License.find_or_create_by(agent_id: 68, state: "IN")
License.find_or_create_by(agent_id: 68, state: "SC")
License.find_or_create_by(agent_id: 68, state: "WY")
Agent.find(68).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(68).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(68).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(68).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 69, state: "ND")
License.find_or_create_by(agent_id: 69, state: "AK")
License.find_or_create_by(agent_id: 69, state: "TX")
License.find_or_create_by(agent_id: 69, state: "LA")
License.find_or_create_by(agent_id: 69, state: "WV")
License.find_or_create_by(agent_id: 69, state: "MO")
License.find_or_create_by(agent_id: 69, state: "OK")
Agent.find(69).carriers << Carrier.find_by_name('Big City Business Insurance')
License.find_or_create_by(agent_id: 70, state: "GA")
License.find_or_create_by(agent_id: 70, state: "IA")
License.find_or_create_by(agent_id: 70, state: "NM")
License.find_or_create_by(agent_id: 70, state: "MA")
License.find_or_create_by(agent_id: 70, state: "NY")
License.find_or_create_by(agent_id: 70, state: "ID")
License.find_or_create_by(agent_id: 70, state: "KY")
License.find_or_create_by(agent_id: 70, state: "NV")
Agent.find(70).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(70).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 71, state: "VT")
License.find_or_create_by(agent_id: 71, state: "IA")
License.find_or_create_by(agent_id: 71, state: "NV")
License.find_or_create_by(agent_id: 71, state: "FL")
License.find_or_create_by(agent_id: 71, state: "AL")
License.find_or_create_by(agent_id: 71, state: "MI")
License.find_or_create_by(agent_id: 71, state: "MO")
Agent.find(71).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(71).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 72, state: "SC")
License.find_or_create_by(agent_id: 72, state: "NE")
License.find_or_create_by(agent_id: 72, state: "NC")
License.find_or_create_by(agent_id: 72, state: "NM")
Agent.find(72).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(72).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 73, state: "HI")
License.find_or_create_by(agent_id: 73, state: "OK")
License.find_or_create_by(agent_id: 73, state: "TN")
License.find_or_create_by(agent_id: 73, state: "ID")
License.find_or_create_by(agent_id: 73, state: "SD")
License.find_or_create_by(agent_id: 73, state: "NY")
Agent.find(73).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(73).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 74, state: "OK")
License.find_or_create_by(agent_id: 74, state: "TN")
License.find_or_create_by(agent_id: 74, state: "CO")
License.find_or_create_by(agent_id: 74, state: "IL")
Agent.find(74).carriers << Carrier.find_by_name('Statewide')
Agent.find(74).carriers << Carrier.find_by_name('Safestate')
Agent.find(74).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(74).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 75, state: "WV")
License.find_or_create_by(agent_id: 75, state: "WA")
License.find_or_create_by(agent_id: 75, state: "IN")
License.find_or_create_by(agent_id: 75, state: "MI")
Agent.find(75).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(75).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(75).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 76, state: "CA")
License.find_or_create_by(agent_id: 76, state: "TX")
License.find_or_create_by(agent_id: 76, state: "MI")
License.find_or_create_by(agent_id: 76, state: "VT")
License.find_or_create_by(agent_id: 76, state: "ME")
License.find_or_create_by(agent_id: 76, state: "MT")
License.find_or_create_by(agent_id: 76, state: "HI")
Agent.find(76).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(76).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 77, state: "ND")
License.find_or_create_by(agent_id: 77, state: "CA")
Agent.find(77).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(77).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 78, state: "CA")
License.find_or_create_by(agent_id: 78, state: "VT")
License.find_or_create_by(agent_id: 78, state: "ND")
License.find_or_create_by(agent_id: 78, state: "AK")
License.find_or_create_by(agent_id: 78, state: "WV")
License.find_or_create_by(agent_id: 78, state: "OK")
Agent.find(78).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(78).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 79, state: "VA")
License.find_or_create_by(agent_id: 79, state: "OR")
License.find_or_create_by(agent_id: 79, state: "MN")
License.find_or_create_by(agent_id: 79, state: "MI")
License.find_or_create_by(agent_id: 79, state: "OH")
Agent.find(79).carriers << Carrier.find_by_name('Statewide')
Agent.find(79).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(79).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(79).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 80, state: "MI")
License.find_or_create_by(agent_id: 80, state: "NY")
License.find_or_create_by(agent_id: 80, state: "TX")
License.find_or_create_by(agent_id: 80, state: "TN")
License.find_or_create_by(agent_id: 80, state: "WY")
Agent.find(80).carriers << Carrier.find_by_name('Homestate')
Agent.find(80).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(80).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 81, state: "NE")
License.find_or_create_by(agent_id: 81, state: "CA")
License.find_or_create_by(agent_id: 81, state: "ID")
License.find_or_create_by(agent_id: 81, state: "UT")
License.find_or_create_by(agent_id: 81, state: "IA")
Agent.find(81).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(81).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(81).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 82, state: "MA")
License.find_or_create_by(agent_id: 82, state: "NC")
License.find_or_create_by(agent_id: 82, state: "DE")
Agent.find(82).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(82).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 83, state: "IA")
License.find_or_create_by(agent_id: 83, state: "RI")
Agent.find(83).carriers << Carrier.find_by_name('Statewide')
Agent.find(83).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(83).carriers << Carrier.find_by_name('Safestate')
Agent.find(83).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 84, state: "IA")
License.find_or_create_by(agent_id: 84, state: "NV")
Agent.find(84).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(84).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(84).carriers << Carrier.find_by_name('Statewide')
Agent.find(84).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 85, state: "NV")
License.find_or_create_by(agent_id: 85, state: "NJ")
License.find_or_create_by(agent_id: 85, state: "CA")
License.find_or_create_by(agent_id: 85, state: "TX")
License.find_or_create_by(agent_id: 85, state: "NY")
Agent.find(85).carriers << Carrier.find_by_name('Statewide')
Agent.find(85).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(85).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(85).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 86, state: "NY")
License.find_or_create_by(agent_id: 86, state: "VT")
License.find_or_create_by(agent_id: 86, state: "GA")
License.find_or_create_by(agent_id: 86, state: "UT")
License.find_or_create_by(agent_id: 86, state: "WV")
Agent.find(86).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(86).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(86).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 87, state: "KY")
License.find_or_create_by(agent_id: 87, state: "AL")
License.find_or_create_by(agent_id: 87, state: "TN")
License.find_or_create_by(agent_id: 87, state: "NE")
Agent.find(87).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(87).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 88, state: "TX")
License.find_or_create_by(agent_id: 88, state: "WI")
License.find_or_create_by(agent_id: 88, state: "NV")
License.find_or_create_by(agent_id: 88, state: "SC")
Agent.find(88).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(88).carriers << Carrier.find_by_name('Homestate')
Agent.find(88).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(88).carriers << Carrier.find_by_name('Safestate')
License.find_or_create_by(agent_id: 89, state: "HI")
License.find_or_create_by(agent_id: 89, state: "TN")
License.find_or_create_by(agent_id: 89, state: "NV")
License.find_or_create_by(agent_id: 89, state: "OH")
License.find_or_create_by(agent_id: 89, state: "MN")
License.find_or_create_by(agent_id: 89, state: "VT")
Agent.find(89).carriers << Carrier.find_by_name('Safestate')
Agent.find(89).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(89).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(89).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 90, state: "MI")
License.find_or_create_by(agent_id: 90, state: "ME")
License.find_or_create_by(agent_id: 90, state: "SD")
License.find_or_create_by(agent_id: 90, state: "AR")
License.find_or_create_by(agent_id: 90, state: "NC")
License.find_or_create_by(agent_id: 90, state: "MT")
License.find_or_create_by(agent_id: 90, state: "TN")
Agent.find(90).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(90).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 91, state: "NC")
License.find_or_create_by(agent_id: 91, state: "UT")
License.find_or_create_by(agent_id: 91, state: "KY")
License.find_or_create_by(agent_id: 91, state: "NM")
License.find_or_create_by(agent_id: 91, state: "TN")
License.find_or_create_by(agent_id: 91, state: "CA")
License.find_or_create_by(agent_id: 91, state: "AZ")
License.find_or_create_by(agent_id: 91, state: "ID")
Agent.find(91).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(91).carriers << Carrier.find_by_name('Statewide')
Agent.find(91).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(91).carriers << Carrier.find_by_name('Big City Business Insurance')
License.find_or_create_by(agent_id: 92, state: "UT")
Agent.find(92).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(92).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(92).carriers << Carrier.find_by_name('Safestate')
License.find_or_create_by(agent_id: 93, state: "CT")
License.find_or_create_by(agent_id: 93, state: "CO")
License.find_or_create_by(agent_id: 93, state: "WA")
Agent.find(93).carriers << Carrier.find_by_name('Safestate')
Agent.find(93).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 94, state: "WA")
License.find_or_create_by(agent_id: 94, state: "RI")
License.find_or_create_by(agent_id: 94, state: "WV")
License.find_or_create_by(agent_id: 94, state: "IN")
Agent.find(94).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(94).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 95, state: "NC")
License.find_or_create_by(agent_id: 95, state: "MS")
Agent.find(95).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(95).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 96, state: "NE")
License.find_or_create_by(agent_id: 96, state: "ME")
License.find_or_create_by(agent_id: 96, state: "MT")
License.find_or_create_by(agent_id: 96, state: "WI")
Agent.find(96).carriers << Carrier.find_by_name('Safestate')
Agent.find(96).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 97, state: "MT")
License.find_or_create_by(agent_id: 97, state: "NM")
License.find_or_create_by(agent_id: 97, state: "NE")
Agent.find(97).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(97).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 98, state: "VT")
License.find_or_create_by(agent_id: 98, state: "UT")
License.find_or_create_by(agent_id: 98, state: "TX")
License.find_or_create_by(agent_id: 98, state: "TN")
License.find_or_create_by(agent_id: 98, state: "KY")
License.find_or_create_by(agent_id: 98, state: "OK")
License.find_or_create_by(agent_id: 98, state: "IN")
Agent.find(98).carriers << Carrier.find_by_name('Statewide')
Agent.find(98).carriers << Carrier.find_by_name('Homestate')
Agent.find(98).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 99, state: "OK")
License.find_or_create_by(agent_id: 99, state: "NM")
License.find_or_create_by(agent_id: 99, state: "NY")
License.find_or_create_by(agent_id: 99, state: "HI")
License.find_or_create_by(agent_id: 99, state: "OR")
Agent.find(99).carriers << Carrier.find_by_name('Safestate')
Agent.find(99).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(99).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 100, state: "KS")
License.find_or_create_by(agent_id: 100, state: "AR")
License.find_or_create_by(agent_id: 100, state: "NH")
Agent.find(100).carriers << Carrier.find_by_name('Safestate')
Agent.find(100).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 101, state: "WA")
License.find_or_create_by(agent_id: 101, state: "HI")
License.find_or_create_by(agent_id: 101, state: "LA")
License.find_or_create_by(agent_id: 101, state: "CA")
License.find_or_create_by(agent_id: 101, state: "AK")
License.find_or_create_by(agent_id: 101, state: "UT")
License.find_or_create_by(agent_id: 101, state: "FL")
Agent.find(101).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(101).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(101).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 102, state: "IN")
License.find_or_create_by(agent_id: 102, state: "WA")
License.find_or_create_by(agent_id: 102, state: "MI")
License.find_or_create_by(agent_id: 102, state: "IL")
License.find_or_create_by(agent_id: 102, state: "VA")
Agent.find(102).carriers << Carrier.find_by_name('Homestate')
Agent.find(102).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(102).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(102).carriers << Carrier.find_by_name('Statewide')
License.find_or_create_by(agent_id: 103, state: "IA")
License.find_or_create_by(agent_id: 103, state: "WV")
License.find_or_create_by(agent_id: 103, state: "NY")
License.find_or_create_by(agent_id: 103, state: "NH")
Agent.find(103).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(103).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 104, state: "AR")
License.find_or_create_by(agent_id: 104, state: "DE")
License.find_or_create_by(agent_id: 104, state: "NH")
License.find_or_create_by(agent_id: 104, state: "IL")
Agent.find(104).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(104).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(104).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 105, state: "KS")
License.find_or_create_by(agent_id: 105, state: "AR")
License.find_or_create_by(agent_id: 105, state: "WI")
License.find_or_create_by(agent_id: 105, state: "NJ")
License.find_or_create_by(agent_id: 105, state: "VT")
License.find_or_create_by(agent_id: 105, state: "WV")
License.find_or_create_by(agent_id: 105, state: "AL")
Agent.find(105).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(105).carriers << Carrier.find_by_name('Homestate')
Agent.find(105).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(105).carriers << Carrier.find_by_name('Cold Weather Insurance')
License.find_or_create_by(agent_id: 106, state: "GA")
License.find_or_create_by(agent_id: 106, state: "OH")
License.find_or_create_by(agent_id: 106, state: "WY")
Agent.find(106).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(106).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(106).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(106).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 107, state: "TN")
License.find_or_create_by(agent_id: 107, state: "AK")
Agent.find(107).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(107).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(107).carriers << Carrier.find_by_name('Prestige Worldwide')
License.find_or_create_by(agent_id: 108, state: "KS")
License.find_or_create_by(agent_id: 108, state: "CO")
License.find_or_create_by(agent_id: 108, state: "NE")
License.find_or_create_by(agent_id: 108, state: "NV")
License.find_or_create_by(agent_id: 108, state: "NH")
License.find_or_create_by(agent_id: 108, state: "ME")
License.find_or_create_by(agent_id: 108, state: "CA")
Agent.find(108).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(108).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 109, state: "NJ")
License.find_or_create_by(agent_id: 109, state: "MO")
License.find_or_create_by(agent_id: 109, state: "MN")
License.find_or_create_by(agent_id: 109, state: "CA")
License.find_or_create_by(agent_id: 109, state: "CO")
License.find_or_create_by(agent_id: 109, state: "LA")
License.find_or_create_by(agent_id: 109, state: "VT")
License.find_or_create_by(agent_id: 109, state: "UT")
Agent.find(109).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(109).carriers << Carrier.find_by_name('Freedom Insurance Company')
License.find_or_create_by(agent_id: 110, state: "TX")
License.find_or_create_by(agent_id: 110, state: "AR")
License.find_or_create_by(agent_id: 110, state: "KY")
Agent.find(110).carriers << Carrier.find_by_name('Iguana Insure')
Agent.find(110).carriers << Carrier.find_by_name('Safestate')
Agent.find(110).carriers << Carrier.find_by_name('Homestate')
Agent.find(110).carriers << Carrier.find_by_name('PenguinTech')
License.find_or_create_by(agent_id: 111, state: "AZ")
License.find_or_create_by(agent_id: 111, state: "WV")
License.find_or_create_by(agent_id: 111, state: "IL")
License.find_or_create_by(agent_id: 111, state: "NY")
License.find_or_create_by(agent_id: 111, state: "MS")
License.find_or_create_by(agent_id: 111, state: "SD")
Agent.find(111).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(111).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 112, state: "DE")
License.find_or_create_by(agent_id: 112, state: "WA")
License.find_or_create_by(agent_id: 112, state: "MT")
License.find_or_create_by(agent_id: 112, state: "CO")
Agent.find(112).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(112).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(112).carriers << Carrier.find_by_name('Safestate')
License.find_or_create_by(agent_id: 113, state: "CT")
License.find_or_create_by(agent_id: 113, state: "MI")
License.find_or_create_by(agent_id: 113, state: "OK")
License.find_or_create_by(agent_id: 113, state: "VT")
Agent.find(113).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(113).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 114, state: "OK")
License.find_or_create_by(agent_id: 114, state: "MD")
License.find_or_create_by(agent_id: 114, state: "FL")
License.find_or_create_by(agent_id: 114, state: "KY")
License.find_or_create_by(agent_id: 114, state: "MS")
Agent.find(114).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(114).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 115, state: "IL")
License.find_or_create_by(agent_id: 115, state: "MI")
License.find_or_create_by(agent_id: 115, state: "RI")
License.find_or_create_by(agent_id: 115, state: "FL")
License.find_or_create_by(agent_id: 115, state: "AR")
Agent.find(115).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(115).carriers << Carrier.find_by_name('Allen & Associates')
Agent.find(115).carriers << Carrier.find_by_name('Homestate')
License.find_or_create_by(agent_id: 116, state: "AK")
License.find_or_create_by(agent_id: 116, state: "VT")
License.find_or_create_by(agent_id: 116, state: "MS")
License.find_or_create_by(agent_id: 116, state: "MO")
Agent.find(116).carriers << Carrier.find_by_name('Prestige Worldwide')
Agent.find(116).carriers << Carrier.find_by_name('Polaris International Risk')
License.find_or_create_by(agent_id: 117, state: "KY")
License.find_or_create_by(agent_id: 117, state: "RI")
License.find_or_create_by(agent_id: 117, state: "MS")
Agent.find(117).carriers << Carrier.find_by_name('FarmInsure')
Agent.find(117).carriers << Carrier.find_by_name('Safestate')
Agent.find(117).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(117).carriers << Carrier.find_by_name('Iguana Insure')
License.find_or_create_by(agent_id: 118, state: "LA")
License.find_or_create_by(agent_id: 118, state: "IA")
License.find_or_create_by(agent_id: 118, state: "MS")
License.find_or_create_by(agent_id: 118, state: "AZ")
License.find_or_create_by(agent_id: 118, state: "TX")
Agent.find(118).carriers << Carrier.find_by_name('Big City Business Insurance')
Agent.find(118).carriers << Carrier.find_by_name('Polaris International Risk')
Agent.find(118).carriers << Carrier.find_by_name('Allen & Associates')
License.find_or_create_by(agent_id: 119, state: "WY")
License.find_or_create_by(agent_id: 119, state: "MT")
License.find_or_create_by(agent_id: 119, state: "TX")
License.find_or_create_by(agent_id: 119, state: "MS")
License.find_or_create_by(agent_id: 119, state: "AR")
Agent.find(119).carriers << Carrier.find_by_name('PenguinTech')
Agent.find(119).carriers << Carrier.find_by_name('Freedom Insurance Company')
Agent.find(119).carriers << Carrier.find_by_name('FarmInsure')
License.find_or_create_by(agent_id: 120, state: "SC")
License.find_or_create_by(agent_id: 120, state: "MA")
License.find_or_create_by(agent_id: 120, state: "OH")
License.find_or_create_by(agent_id: 120, state: "IL")
Agent.find(120).carriers << Carrier.find_by_name('Cold Weather Insurance')
Agent.find(120).carriers << Carrier.find_by_name('Safestate')
Agent.find(120).carriers << Carrier.find_by_name('Statewide')
